contacts/__init__.py
# -*- coding: utf-8 -*-

"""
.. module:: .__init__.py.py
   :synopsis: <write a synopsis>

.. moduleauthor:: Athanasios Rigas
                  <admin@ithemis.gr>
"""

contacts/app.py
# -*- coding: utf-8 -*-

"""
.. module:: .contacts.py
   :synopsis: <write a synopsis>

.. moduleauthor:: Athanasios Rigas
                  <admin@ithemis.gr>
"""

from flask import Flask

from config.config import configure_app
from contacts.utils.filters import pluralize


def create_app():
    app = Flask(__name__)
    configure_app(app)

    # Add your custom filter
    app.jinja_env.filters['pluralize'] = pluralize

    return app

contacts/decorators/__init__.py
# -*- coding: utf-8 -*-

"""
.. module:: .__init__.py.py
   :synopsis: <write a synopsis>

.. moduleauthor:: Athanasios Rigas
                  <admin@ithemis.gr>
"""

contacts/utils/__init__.py
# -*- coding: utf-8 -*-

"""
.. module:: .__init__.py.py
   :synopsis: <write a synopsis>

.. moduleauthor:: Athanasios Rigas
                  <admin@ithemis.gr>
"""

contacts/views.py
# -*- coding: utf-8 -*-

"""
.. module:: .views.py
   :synopsis: <write a synopsis>

.. moduleauthor:: Athanasios Rigas
                  <admin@ithemis.gr>
"""

from flask import Blueprint, request

from contacts.decorators.contacts import contacts_all
from contacts.decorators.contacts_filter import contacts_filter

contacts = Blueprint('contacts', __name__,
                     template_folder='templates',
                     static_folder='static',
                     static_url_path='/contacts/static')


@contacts.route('/')
@contacts_all
def index():
    """
    The starting point
    """
    return request.args


@contacts.route('/results', methods=['POST'])
@contacts_filter
def results():
    """
    Search endpoint
    """
    return request.args

contacts/templates/405.html
{% extends "base.html" %}
{% block title %}{{ super() }} - Method Not Allowed{% endblock %}
{% block content %}
  <h1>Method Not Allowed</h1>
    <p>
        The method is not allowed for the requested URL.
    </p>
    <p>
        Error details: <b>{{ error }}</b>
    </p>
{% endblock %}

contacts/templates/410.html
{% extends "base.html" %}
{% block title %}{{ super() }} - Gone{% endblock %}
{% block content %}
  <h1>Gone</h1>
    <p>
        Page deleted or gone.
    </p>
    <p>
        Error details: <b>{{ error }}</b>
    </p>
{% endblock %}

contacts/templates/base.html
<!DOCTYPE html>
<head>
    {% block head %}
    <title>{% block title %}My awesome app{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('contacts.static', filename='css/styles.css') }}">
    {% endblock %}
</head>

<body>

<div id="search">
    {% block search %}{% endblock %}
</div>

<div id="content">
    {% block content %}{% endblock %}
</div>

<div id="footer">
    {% block footer %}
        <div class="footer-text">
            &copy; My awesome app - <script>document.write(new Date().getFullYear());</script>
        </div>
    {% endblock %}
</div>

</body>
</html>

contacts/templates/index.html
{% extends "base.html" %}
{% block title %}{{ super() }}{% endblock %}

{% block search %}
    <p>Search your contacts</p>
    <form action="{{ url_for('contacts.results') }}" method="post">
        <input type="text" class="searchTerm" name='searchTerm' placeholder="What are you looking for?">
        <button type="submit" class="searchButton">
            Search
        </button>
    </form>
{% endblock %}

{% block content %}
    {% if contacts %}
        {% if request.path == '/' or request.path == '/results' and not searchterm %}
            <p>There are {{ count }} record{{ count|pluralize('', 's') }} in your contact list.</p>
        {% elif request.path == '/results' and searchterm %}
            <p>Found {{ count }} record{{ count|pluralize('', 's') }} for "{{ searchterm }}":</p>
        {% endif %}

        <table id="contacts">
            <thead>
                <th>Job history</th>
                <th>Company</th>
                <th>Email</th>
                <th>City</th>
                <th>Name</th>
                <th>Country</th>
            </thead>

            <tbody id="table-body">
                {% for contact in contacts %}
                    <tr>
                        {% for value in contact.values() %}
                            <td> {{ value }} </td>
                        {% endfor %}
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>No records found for "{{ searchterm }}"!</p>
    {% endif %}
{% endblock %}